# Generated by Django 6.0.3 on 2026-04-04 06:46

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_websitebranding_websitefooter_websitetheme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('items', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(default='Bulk Order Received', max_length=40)),
                ('shipping_address', models.JSONField(default=dict)),
                ('bulk_status', models.CharField(default='Pending Manager Review', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bulk_orders',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('shop_type', models.CharField(default='Normal', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('banner_image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'main_categories',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='banner_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='category',
            name='banner_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='api.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='coupon',
            table='coupons',
        ),
        migrations.AlterModelTable(
            name='hero',
            table='heroes',
        ),
        migrations.AlterModelTable(
            name='navigation',
            table='navigation',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='page',
            table='pages',
        ),
        migrations.AlterModelTable(
            name='policy',
            table='policies',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='promotion',
            table='promotions',
        ),
        migrations.AlterModelTable(
            name='story',
            table='stories',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.maincategory')),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
    ]
