# Generated by Django 5.2.12 on 2026-04-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bulkorder_maincategory_category_banner_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dropdown',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='shop_type',
            field=models.CharField(db_column='shop', default='Normal', max_length=50),
        ),
    ]
